apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: vault-client
  labels:
    app: vault-client
spec:
  serviceAccountName: vault-auth
  containers:
    - name: app
      image: docker.io/library/k8s-vault-client
      imagePullPolicy: IfNotPresent
      env:
      - name: VAULT_ADDR
        value: "http://192.168.65.254:8200"
      - name: VAULT_TOKEN
        value: root
